# ++++++++++++++++++++
# NEUZZ Configurations 
# ++++++++++++++++++++

# Configurations for the bridge between C and Neuzz
socket:
  HOST: '127.0.0.1' # Host address.
  PORT: 12012       # Port to talk at.
  RECV_BUFF: 1024   # Buffer Length of socket receive 
                    # (keep this small and as a power of 2).

# Configurations for the Neural Network model
model:
  batch_size: 16 # Batch Size
  epochs: 100    # Number of Epochs
  aplha: 0.0001  # Learning rate
  layers:
    n_layers: 1          # Number of intermediate layers (not incl. output)
    layer1:
      name: "hidden_1"   # Name of the hidden layer 
      n_neurons: 4096    # Number of neurons
      activation: "RELU" # Activation function
    output:
      name: "output"
      activation: "sigmoid"

# Configurations for running the fuzzer
fuzz:
  bitmap_len: 0    # The number of output branches to use to measure the 
                   # coverage 0 means, use all branches.
  labeling: "hard" # Labeling strategy. Use either "hard" or "soft"

# System Options for limiting how the FUZZER is run
sys:
  gpu_mem_frac: 0.33  # Fraction of GPU memory assigned to a Tensorflow Job. 
                      # Assuming a 12 GB GPU, we assign a max of 4GB for a task

