# NEUZZ Configurations 
# --------------------

# Configurations for the bridge between C and Neuzz
socket:
  HOST: '127.0.0.1' # Host address.
  PORT: 12012       # Port to talk at.
  RECV_BUFF: 1024   # Buffer Length of socket receive 
                    # (keep this small and as a power of 2).

# Configurations for fuzzing target data
## ** DON'T TOUCH ** 
## These are placeholders that'll be changed later on in the code. Modifying 
## them will have no effect.
data:
  MAX_FILE_SIZE: 10000  # DON'T CHANGE
  MAX_BITMAP_SIZE: 2000 # DON'T CHANGE

# Configurations for the Neural Network model
model:
  batch_size: 16 # Batch Size
  epochs: 100 # Number of Epochs
  aplha: 0.0001 # Learning rate
  layers:
    n_layers: 1 # Number of intermediate layers (Not including input/output)
    layer1:
      name: "hidden_1" # Name of the hidden layer 
      n_neurons: 4096 # Number of neurons
      activation: "RELU" # Activation function
    output:
      name: "output"
      activation: "sigmoid"
    

    



